### PR TITLE
When publishing a video to voctoweb, generate and upload Timelens files

### PR DESCRIPTION
**Pull request by blinry**
Please review this pull request carefully. While the code has been written with utmost care, it has not actually been tested, as I didn't set up my own c3tt instance. Will there be a way for you to test this?

### CODE REVIEW

**Comment by derpeter** [comment]
LGTM thanks you. One question, as i don't have experience with timelens yet: Would it make sense to you to add the parameters you hardcoded as ticket properties or are they fixed per voctoweb instance?

**Comment by blinry** [comment]
The visual timelines are all displayed with the same width in the voctoweb interface, so it makes sense for all of them to have the same size. On second thought, I've changed the height to 90 pixels, to better fit the common 16:9 resolution without rounding the thumbnail sizes.

**Comment by a-tze** [comment]
Ok my guess was that browser side scaling does NOT work flawlessly, especially with such sharp-edged content, but maybe thats knowledge from the past.

**Comment by MaZderMind** [comment]
Just a note: most modern browsers do support the selection of different mage Scaling Algorithms: 
https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering
https://css-tricks.com/almanac/properties/i/image-rendering/

**Comment by derpeter** [comment]
You guys lost me somewhere. My question was if e.g. someone running a different themed vocotoweb instance would want to alter these parameters. Or even if we would do that. In that case i would move the parameters either to the ini file or a tracker property

**Comment by blinry** [comment]
@derpeter: Ah, I see. Hm, I could imagine that in 10 years, when the average Internet connection speed, CPU power, and screen resolution has gone way up, I'd prefer a width of 1920 pixels or so, to make the Timelens interface even more expressive. I wouldn't worry about that now.

@MaZderMind: Interesting! I think smoothing scaling algorithms are desirable here, so I'm happy with the default value of "auto".

**Comment by blinry** [comment]
Now that voctoweb has [Timelens support](https://github.com/voc/voctoweb/pull/327), this PR would allow generating the required files for upcoming events! \o/

Is there already configuration management in place to make sure Timelens gets installed on the publishing machine?

I guess it would also make sense to write a script which retroactively generates the files for old events, similar to [rebuild-images.pl](https://github.com/voc/voctopublish/blob/fdbcd71055662d843305d253fdcde8cd668f32b6/postprocessing/rebuild_images/rebuild_images.pl), right? I can look into that in the next weeks! :)

**Comment by derpeter** [comment]
@blinry as its only one machine i installed timelens by hand. (But of course we should put it into the ansible eventually).

I'm planning to test and merge your PR at the weekend at the VCFB.

Yes rebuild script is the next step but it is a little more complex as we need to add the new values to the database. I'm not 100% sure jet what will be the best way to do this. 
AFAIR we will need to speak to both APIs (public and privat) to achieve this.
I hope i find the time to implement this soonisch.

**Pull request merged**
